spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: llava   # Multimodal model, supports image+text input

queue:
  engineRequestQueue: markdown-engine-queue

transform:
  core:
    version: 5.1.7
  language:
    default: english    # Accepted languages: english, spanish, french, german, italian, portuguese
