spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: llava   # Multimodal model, supports image+text input

queue:
  engineRequestQueue: markdown-engine-queue

transform:
  core:
    version: 5.1.7
  language:
    default: english    # Accepted languages: english, spanish, french, german, italian, portuguese
  image:
    default: placeholder # Accepted options: placeholder, embedded, referenced, described

# Image options:
# * placeholder: only the position of the image is marked in the output
# * embedded: the image is embedded as base64 encoded string
# * referenced: the image is exported in PNG format and referenced from the main exported document
# * described: the image description is embedded in the position of the image. This is not a native Docling option.
